@startuml

!include _defaults.puml

title Entity Relationship Diagram

hide circle
skinparam Linetype ortho

entity "Users" as entUsers {
    * UserId : uuid <<PK>>
    --
    * Username : string <<unique>>
    * PasswordHash : string
    * PasswordSalt : string
    Email : string
}

entity "Licenses" as entLicenses {
    * LicenseNumber : string <<PK>>
    --
    * UserId : uuid <<FK>>
    * ExpirationDate : Date
    * ACategory : bool
    * BCategory : bool
    Issuer : string
    IssueDate : Date
}

entUsers ||-o| entLicenses

entity "Vehicles" as entVehicles {
    * VehiclePlate : string <<PK>>
    --
    * DriverLicenseNumber : string <<FK>>
}

entLicenses |o-|| entVehicles

@enduml
