version: '3.9'

services:

  red-cobra-db:
    image: postgres:latest
    container_name: 'red-cobra-db'
    restart: unless-stopped
    hostname: 'red-cobra-db'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    security_opt:
      - no-new-privileges:true
    shm_size: 128mb
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'America/Sao_Paulo'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ${POSTGRES_PGDATA}:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - red-cobra-net

  red-cobra-prometheus:
    image: prom/prometheus:latest
    container_name: 'red-cobra-prometheus'
    restart: unless-stopped
    hostname: 'red-cobra-prometheus'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'America/Sao_Paulo'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROMETHEUS_CONFIG}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_APP}:/prometheus
    networks:
      - red-cobra-net

networks:
  red-cobra-net:
    name: red-cobra-net
