version: '3.9'

services:

  red-cobra-db:
    container_name: 'red-cobra-db'
    image: postgres:latest
    restart: unless-stopped
    hostname: 'red-cobra-db'
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - ${POSTGRES_PGDATA}:/var/lib/postgresql/data
    ports:
      - '5432:5432'
